### ISSUE TITLE
Tanzania1991 : birth data not found

### ISSUE THREAD

**Issue by robin-wang** [wengxyu1030/DHS-Recode-II#2]
"file C:/Users/XWeng/OneDrive - WBG/MEASURE UHC DATA/RAW DATA/Recode II/DHS-Tanzania1991/DHS-Tanzania1991birth.dta not found"

- DW rerun with pause in the zsc section, then birth data could be read into programme successfully.
- Additional raw data uploaded
- variables hv001 hm_shstruct hv002 hvidx do not uniquely identify observations in the master data

**Comment by wengxyu1030** [comment]
With data downloaded instead of having them in the OneDrive cloud, the issue solved.
